export const HIDE_LOADING = 'HIDE_LOADING'
export const SHOW_LOADING = 'SHOW_LOADING'
export const ADD_CARTS = 'ADD_CARTS'// 加入购物车
export const DEC_CARTS = 'DEC_CARTS'// 删减购物车
export const SED_MSG = 'SED_MSG'
export const GET_MSG = 'GET_MSG'
export const CLEAR_ALL = 'CLEAR_ALL'// 清空购物车
export const FULL_ALL = 'FULL_ALL'// 填充购物车
export const ADD_USER = 'ADD_USER'// 登陆
export const REMOVE_USER = 'REMOVE_USER'// 注销
